from __future__ import annotations


_SCRIPT_HEADER = r"""const PRODUCT_UI = __PRODUCT_UI_CONFIG__, darkIcon = '__DARK_ICON__', lightIcon = '__LIGHT_ICON__';
const $ = id => document.getElementById(id);
const state = { session: null, csrfToken: '', conversation: [], chatSessionId: null, isStreaming: false, stopRequested: false, stopIntent: false, chatAbortController: null, adminUsers: [], signupLink: '', workspace: { currentPath: '', entries: [], usedBytes: 0, limitBytes: 0 }, isUploading: false, isCreatingFolder: false, isBooting: true, draggedWorkspacePath: '', isClaimingInvite: false };
const themeToggle = $('themeToggle'), logoutButton = $('logoutButton'), authMessage = $('authMessage'), sessionChip = $('sessionChip'), loginButton = $('loginButton'), claimInviteButton = $('claimInviteButton'), bootCard = $('bootCard'), authCard = $('authCard'), chatCard = $('chatCard'), workspaceCard = $('workspaceCard'), adminCard = $('adminCard'), chatLog = $('chatLog'), chatForm = $('chatForm'), chatInput = $('chatInput'), chatSubmit = $('chatSubmit'), chatStop = $('chatStop'), chatMessage = $('chatMessage'), workspaceMessage = $('workspaceMessage'), workspaceUsageLabel = $('workspaceUsageLabel'), workspaceUsageBar = $('workspaceUsageBar'), workspacePathLabel = $('workspacePathLabel'), workspaceUpButton = $('workspaceUpButton'), workspaceUploadForm = $('workspaceUploadForm'), workspaceDropzone = $('workspaceDropzone'), workspaceFileInput = $('workspaceFileInput'), workspaceUploadButton = $('workspaceUploadButton'), workspaceFolderForm = $('workspaceFolderForm'), workspaceFolderName = $('workspaceFolderName'), workspaceFolderButton = $('workspaceFolderButton'), workspaceFolderSubmitButton = $('workspaceFolderSubmitButton'), workspaceTable = $('workspaceTable'), adminUsersTable = $('adminUsersTable'), adminMessage = $('adminMessage'), adminCreateUserForm = $('adminCreateUserForm'), adminCreateUserButton = $('adminCreateUserButton'), adminDisplayNameInput = $('adminDisplayNameInput'), adminSignupTokenCard = $('adminSignupTokenCard'), adminSignupTokenUrl = $('adminSignupTokenUrl'), adminCopySignupLinkButton = $('adminCopySignupLinkButton');
const workspaceIcons = {
  folder: '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M3.75 7.5h5.1l1.8 2.25h9.6v8.25A2.25 2.25 0 0 1 18 20.25H6A2.25 2.25 0 0 1 3.75 18V7.5Z\"></path><path d=\"M3.75 9.75V6A2.25 2.25 0 0 1 6 3.75h3.75l1.8 2.25H18A2.25 2.25 0 0 1 20.25 8.25\"></path></svg>',
  file: '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M8.25 3.75h6l4.5 4.5v10.5a1.5 1.5 0 0 1-1.5 1.5H8.25a3 3 0 0 1-3-3V6.75a3 3 0 0 1 3-3Z\"></path><path d=\"M14.25 3.75v4.5h4.5M9 12h6M9 15.75h6\"></path></svg>'
};
"""

_UTILITY_FUNCTIONS = r"""function esc(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function fmt(value){const text=String(value||'');let out='',cursor=0;while(cursor<text.length){const open=text.indexOf('**',cursor);if(open===-1){out+=esc(text.slice(cursor));break}const close=text.indexOf('**',open+2);if(close===-1){out+=esc(text.slice(cursor));break}out+=esc(text.slice(cursor,open));out+=`<strong>${esc(text.slice(open+2,close))}</strong>`;cursor=close+2}return out}
function setMessage(node,text,kind='neutral'){if(!node)return;node.textContent=text||'';node.classList.remove('is-error');if(kind==='error')node.classList.add('is-error')}
function humanBytes(value){let amount=Math.max(0,Number(value)||0);const units=['B','KB','MB','GB','TB'];let index=0;while(amount>=1024&&index<units.length-1){amount/=1024;index++}if(index===0)return `${Math.round(amount)} ${units[index]}`;if(amount>=10||Math.abs(amount-Math.round(amount))<0.05)return `${Math.round(amount)} ${units[index]}`;return `${amount.toFixed(1)} ${units[index]}`}
function emptyWorkspace(){return {currentPath:'',entries:[],usedBytes:0,limitBytes:0}}
function normalizeWorkspace(payload){return {currentPath:String(payload?.current_path??payload?.currentPath??''),entries:Array.isArray(payload?.entries)?payload.entries:[],usedBytes:Number(payload?.used_bytes??payload?.usedBytes??0),limitBytes:Number(payload?.limit_bytes??payload?.limitBytes??0)}}
function sleep(ms){return new Promise(resolve=>window.setTimeout(resolve,ms))}
function scheduleStoppedMessage(){const apply=()=>{if(state.stopIntent)setMessage(chatMessage,'Response stopped.')};window.setTimeout(apply,300);window.setTimeout(apply,1200)}
function authHeaders(extraHeaders={}){const headers={...extraHeaders};if(state.csrfToken)headers['X-Hermes-CSRF-Token']=state.csrfToken;return headers}
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...authHeaders(options.headers||{})},...options});if(response.status===204)return null;const data=await response.json().catch(()=>({}));if(data&&typeof data==='object'&&typeof data.csrf_token==='string')state.csrfToken=data.csrf_token;if(!response.ok)throw new Error(data.detail||data.error||'Request failed');return data}
function signedIn(){return Boolean(state.session&&state.session.authenticated&&state.session.user)}
function isAdmin(){return Boolean(signedIn()&&state.session.user.is_admin)}
function currentWorkspacePath(){return state.workspace.currentPath||''}
function resetSignedInState(){state.conversation=[];state.chatSessionId=null;state.adminUsers=[];state.signupLink='';state.workspace=emptyWorkspace()}
function clearWorkspaceMoveTargets(){workspaceUpButton.classList.remove('is-drop-target');workspaceTable.querySelectorAll('.workspace-entry.is-drop-target,.workspace-entry-main.is-drop-target,.workspace-open-button.is-drop-target').forEach(node=>node.classList.remove('is-drop-target'))}
function currentDraggedWorkspacePath(event){const explicit=String(state.draggedWorkspacePath||'').trim();if(explicit)return explicit;const dragged=event&&event.dataTransfer?String(event.dataTransfer.getData('text/plain')||'').trim():'';return dragged}
function setWorkspaceFolderFormOpen(open){const isOpen=Boolean(open);workspaceFolderForm.hidden=!isOpen;workspaceFolderButton.innerHTML=isOpen?'&#10005;':'&#65291;';workspaceFolderButton.setAttribute('aria-label',isOpen?'Close folder creator':'Create folder')}
const moonPhases=['🌑','🌒','🌓','🌔','🌕','🌖','🌗','🌘'];
let moonPhaseIndex=0,moonSpinnerTimer=null,adminRefreshTimer=null;
function currentReasoningMoon(){return moonPhases[moonPhaseIndex]||'🌒'}
function updateReasoningMoonSpinners(){document.querySelectorAll('.reasoning-moon').forEach(node=>{node.textContent=moonPhases[moonPhaseIndex]})}
function syncReasoningMoonSpinner(){const hasPendingThinking=Boolean(document.querySelector('.reasoning-moon'));if(hasPendingThinking&&!moonSpinnerTimer){updateReasoningMoonSpinners();moonSpinnerTimer=window.setInterval(()=>{moonPhaseIndex=(moonPhaseIndex+1)%moonPhases.length;updateReasoningMoonSpinners()},180)}else if(!hasPendingThinking&&moonSpinnerTimer){window.clearInterval(moonSpinnerTimer);moonSpinnerTimer=null}}
function syncAdminRefreshTimer(){const shouldRefresh=Boolean(!state.isBooting&&signedIn()&&isAdmin()&&!adminCard.hidden);if(shouldRefresh&&!adminRefreshTimer){adminRefreshTimer=window.setInterval(()=>{refreshAdminUsers(true).catch(()=>{})},3000)}else if(!shouldRefresh&&adminRefreshTimer){window.clearInterval(adminRefreshTimer);adminRefreshTimer=null}}
"""

_RENDER_FUNCTIONS = r"""function renderSession(){const signed=signedIn();bootCard.hidden=!state.isBooting;authCard.hidden=state.isBooting||signed;chatCard.hidden=state.isBooting||!signed;workspaceCard.hidden=state.isBooting||!signed;adminCard.hidden=state.isBooting||!isAdmin();logoutButton.hidden=state.isBooting||!signed;sessionChip.hidden=state.isBooting||!signed;if(state.isBooting){syncAdminRefreshTimer();return}if(!signed){sessionChip.textContent='';sessionChip.setAttribute('href','#');resetSignedInState();const pendingInvite=Boolean(state.session?.pending_invite_claim);const detectedLogin=String(state.session?.detected_tailscale_login||'').trim();const inviteName=String(state.session?.pending_invite_display_name||'').trim();$('heroTitle').textContent=pendingInvite?'Confirm invite claim.':'Sign in with Tailscale.';$('heroLead').textContent=pendingInvite?`You are signed in with Tailscale as ${detectedLogin||'this account'}. Claim ${inviteName||'this invited account'} with this identity?`:state.session?.notice||'This app is available only through your tailnet and authenticates with tsidp.';loginButton.hidden=pendingInvite;claimInviteButton.hidden=!pendingInvite;loginButton.textContent='Sign in with Tailscale';loginButton.href='/api/auth/login';claimInviteButton.textContent=state.isClaimingInvite?'Claiming...':'Claim invite with this account';claimInviteButton.disabled=state.isClaimingInvite;claimInviteButton.classList.toggle('is-pending',state.isClaimingInvite);claimInviteButton.setAttribute('aria-busy',state.isClaimingInvite?'true':'false');if(state.isClaimingInvite&&pendingInvite){setMessage(authMessage,'Claiming account...')}else{setMessage(authMessage,state.session?.notice||'',pendingInvite?'neutral':(state.session?.notice?'error':'neutral'))}renderChat();renderWorkspace();renderAdmin();syncAdminRefreshTimer();return}state.isClaimingInvite=false;loginButton.hidden=false;claimInviteButton.hidden=true;claimInviteButton.classList.remove('is-pending');claimInviteButton.disabled=false;claimInviteButton.setAttribute('aria-busy','false');const user=state.session.user;const label=user.name||user.preferred_username||user.sub;sessionChip.textContent=isAdmin()?`${label} · Admin`:label;sessionChip.setAttribute('href',PRODUCT_UI.accountUrl||'#');setMessage(authMessage,'');renderChat();renderWorkspace();renderAdmin();syncAdminRefreshTimer()}
function renderChat(){const signed=signedIn();chatInput.disabled=!signed||state.isStreaming;chatSubmit.setAttribute('aria-disabled',(!signed||state.isStreaming||!chatInput.value.trim())?'true':'false');chatStop.setAttribute('aria-disabled',(!signed||!state.isStreaming)?'true':'false');if(!signed){chatLog.innerHTML='<div class="empty-state">Sign in to open your chat.</div>';syncReasoningMoonSpinner();return}const visibleConversation=state.conversation.filter(message=>{if(message?.pending)return true;if(message?.role==='user')return true;return Boolean(String(message?.content||'').trim())});if(!visibleConversation.length){chatLog.innerHTML='<div class="empty-state">No messages yet.</div>';syncReasoningMoonSpinner();return}chatLog.innerHTML=visibleConversation.map(message=>{const role=message.role==='user'?'user':'assistant';if(message.pending){const reasoningText=String(message.reasoningText||'').trim();return `<article class="chat-bubble reasoning"><div class="reasoning-heading" aria-live="polite"><span class="reasoning-moon" aria-hidden="true">${currentReasoningMoon()}</span><span>thinking...</span></div><div class="reasoning-stack"><div class="reasoning-text">${reasoningText?esc(reasoningText):''}</div></div></article>`}if(role==='user')return `<article class="chat-bubble user"><span class="chat-role">You</span><div class="chat-content">${fmt(message.content||'')}</div></article>`;return `<article class="chat-bubble assistant"><span class="chat-role">Agent</span><div class="chat-content">${fmt(message.content||'')}</div></article>`}).join('');chatLog.scrollTop=chatLog.scrollHeight;syncReasoningMoonSpinner()}
function renderWorkspace(){const signed=signedIn();workspaceUploadButton.disabled=!signed||state.isUploading;workspaceFolderButton.disabled=!signed||state.isCreatingFolder;workspaceFolderSubmitButton.disabled=!signed||state.isCreatingFolder;workspaceFileInput.disabled=!signed||state.isUploading;workspaceFolderName.disabled=!signed||state.isCreatingFolder;const path=currentWorkspacePath();workspaceUpButton.hidden=!signed||!path;workspaceUpButton.disabled=!signed||!path;if(!signed){workspacePathLabel.textContent='Home';workspaceUsageLabel.textContent='0 B / 0 B used';workspaceUsageBar.style.width='0%';setWorkspaceFolderFormOpen(false);workspaceDropzone.classList.remove('is-active');workspaceTable.innerHTML='<div class="workspace-empty muted-cell">Sign in to use your workspace.</div>';clearWorkspaceMoveTargets();return}setWorkspaceFolderFormOpen(!workspaceFolderForm.hidden);const used=Number(state.workspace.usedBytes||0),limit=Math.max(1,Number(state.workspace.limitBytes||0));workspacePathLabel.textContent=path?`/${path}`:'Home';workspaceUsageLabel.textContent=`${humanBytes(used)} / ${humanBytes(limit)} used`;workspaceUsageBar.style.width=`${Math.min(100,used/limit*100)}%`;const entries=state.workspace.entries||[];if(!entries.length){workspaceTable.innerHTML='<div class="workspace-empty muted-cell">No files or folders in this location yet.</div>';clearWorkspaceMoveTargets();return}workspaceTable.innerHTML=entries.map(entry=>{const isFolder=entry.kind==='folder';const kind=isFolder?'Folder':'File';const icon=isFolder?workspaceIcons.folder:workspaceIcons.file;const deleteButton=`<button class="button secondary-button workspace-delete-button" data-path="${esc(entry.path)}" type="button">Delete</button>`;const action=isFolder?`<button class="button secondary-button workspace-open-button" data-path="${esc(entry.path)}" data-kind="${esc(entry.kind)}" type="button">Open</button>${deleteButton}`:`<a class="button secondary-button workspace-download-button" data-path="${esc(entry.path)}" href="/api/workspace/download?path=${encodeURIComponent(entry.path)}">Download</a>${deleteButton}`;const size=isFolder?'-':humanBytes(entry.size_bytes||0);return `<article class="workspace-entry${isFolder?' workspace-folder-entry':''}" data-path="${esc(entry.path)}" data-kind="${esc(entry.kind)}" draggable="true"><div class="workspace-entry-main${isFolder?' workspace-folder-drop-target':''}" data-path="${esc(entry.path)}" data-kind="${esc(entry.kind)}"><span class="workspace-entry-icon">${icon}</span><div class="workspace-entry-copy"><div class="workspace-entry-name">${esc(entry.name)}</div><div class="workspace-entry-meta">${kind}${isFolder?' · Drop items here':''}</div></div></div><div class="workspace-entry-size">${esc(size)}</div><div class="table-actions">${action}</div></article>`}).join('');clearWorkspaceMoveTargets()}
function renderAdmin(){adminSignupTokenCard.hidden=!state.signupLink;if(adminSignupTokenUrl)adminSignupTokenUrl.textContent=state.signupLink||'';if(!isAdmin()){adminUsersTable.innerHTML='<tr><td colspan="4" class="muted-cell">Admin access required.</td></tr>';return}const currentUserId=state.session?.user?.id||state.session?.user?.sub||'';if(!state.adminUsers.length){adminUsersTable.innerHTML='<tr><td colspan="4" class="muted-cell">No product users yet.</td></tr>';return}adminUsersTable.innerHTML=state.adminUsers.map(user=>{if(user.type==='invite'){return `<tr><td><strong>${esc(user.display_name||'Invite')}</strong></td><td><span class="muted-cell">Unclaimed</span></td><td><span class="table-badge">Pending invite</span></td><td><span class="table-badge">Waiting</span></td></tr>`}const isYou=user.id===currentUserId;const status=user.disabled?'<span class="table-badge is-danger">Disabled</span>':'<span class="table-badge">Active</span>';const action=isYou?'<span class="table-badge">You</span>':user.disabled?'<span class="table-badge">Inactive</span>':`<button class="button secondary-button admin-deactivate-button" data-user-id="${esc(user.id)}" type="button">Deactivate</button>`;return `<tr><td><strong>${esc(user.display_name||user.username||'User')}</strong><br><span class="muted-cell">${esc(user.username||'')}</span></td><td>${esc(user.tailscale_login||user.email||'')}</td><td>${status}</td><td><div class="table-actions">${action}</div></td></tr>`}).join('')}
"""

_DATA_LOADING_FUNCTIONS = r"""async function refreshSession(){try{state.session=await api('/api/auth/session');state.csrfToken=String(state.session?.csrf_token||state.csrfToken||'')}catch(error){state.session={authenticated:false,notice:error.message};setMessage(authMessage,error.message,'error')}finally{state.isBooting=false}renderSession()}
async function refreshChatSession(options={}){const preserveMessage=Boolean(options&&options.preserveMessage)||state.stopIntent;if(!signedIn()){state.conversation=[];state.chatSessionId=null;renderChat();return}try{const payload=await api('/api/chat/session');state.chatSessionId=payload.session_id;state.conversation=payload.messages||[];if(!preserveMessage)setMessage(chatMessage,'');renderChat();return}catch(error){if(String(error?.message||'').includes('starting up')){await sleep(300);const payload=await api('/api/chat/session');state.chatSessionId=payload.session_id;state.conversation=payload.messages||[];if(!preserveMessage)setMessage(chatMessage,'');renderChat();return}state.conversation=[];state.chatSessionId=null;if(!preserveMessage)setMessage(chatMessage,error.message||'Request failed','error');renderChat()}}
async function refreshWorkspace(path=currentWorkspacePath()){if(!signedIn()){state.workspace=emptyWorkspace();renderWorkspace();return}try{const query=path?`?path=${encodeURIComponent(path)}`:'';const payload=await api(`/api/workspace${query}`,{headers:{}});state.workspace=normalizeWorkspace(payload);setMessage(workspaceMessage,'')}catch(error){state.workspace=emptyWorkspace();setMessage(workspaceMessage,error.message,'error')}renderWorkspace()}
async function refreshAdminUsers(preserveMessage=false){if(!isAdmin()){state.adminUsers=[];renderAdmin();return}try{const payload=await api('/api/admin/users');state.adminUsers=payload.users||[];if(!preserveMessage)setMessage(adminMessage,'')}catch(error){state.adminUsers=[];setMessage(adminMessage,error.message,'error')}renderAdmin()}
async function refreshAll(){await refreshSession();if(!signedIn())return;const tasks=[refreshChatSession(),refreshWorkspace()];if(isAdmin())tasks.push(refreshAdminUsers());await Promise.allSettled(tasks)}
"""

_ACTION_FUNCTIONS = r"""async function uploadWorkspaceFiles(files){if(!signedIn()){setMessage(workspaceMessage,'Please sign in first.','error');return}const selected=[...files];if(!selected.length){setMessage(workspaceMessage,'Select at least one file to upload.','error');return}const formData=new FormData();formData.append('path',currentWorkspacePath());selected.forEach(file=>formData.append('files',file));state.isUploading=true;renderWorkspace();try{const response=await fetch('/api/workspace/files',{method:'POST',credentials:'same-origin',headers:authHeaders(),body:formData});const payload=await response.json().catch(()=>({}));if(payload&&typeof payload==='object'&&typeof payload.csrf_token==='string')state.csrfToken=payload.csrf_token;if(!response.ok)throw new Error(payload.detail||'Upload failed');state.workspace=normalizeWorkspace(payload);workspaceFileInput.value='';setMessage(workspaceMessage,'Files uploaded.')}catch(error){setMessage(workspaceMessage,error.message,'error')}finally{state.isUploading=false;workspaceDropzone.classList.remove('is-active');renderWorkspace()}}
async function moveWorkspaceItem(sourcePath,destinationParentPath){if(!signedIn()){setMessage(workspaceMessage,'Please sign in first.','error');return}const source=String(sourcePath||'').trim();if(!source)return;try{state.workspace=normalizeWorkspace(await api('/api/workspace/move',{method:'POST',body:JSON.stringify({source_path:source,destination_parent_path:String(destinationParentPath||'')})}));setMessage(workspaceMessage,'Moved.')}catch(error){setMessage(workspaceMessage,error.message,'error')}finally{state.draggedWorkspacePath='';clearWorkspaceMoveTargets();renderWorkspace()}}
async function streamChatTurn(userMessage){state.chatAbortController=new AbortController();const response=await fetch('/api/chat/turn/stream',{method:'POST',credentials:'same-origin',headers:{...authHeaders(),'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({user_message:userMessage}),signal:state.chatAbortController.signal});if(!response.ok||!response.body){let detail='Request failed';try{const payload=await response.json();if(payload&&typeof payload==='object'&&typeof payload.csrf_token==='string')state.csrfToken=payload.csrf_token;detail=payload.detail||detail}catch{}throw new Error(detail)}const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='',eventName='message',dataLines=[],sawFinal=false;const dispatch=(name,payload)=>{if(name==='start'){state.chatSessionId=payload.session_id||state.chatSessionId;return}if(name==='reasoning'){const pending=state.conversation[state.conversation.length-1];const chunk=String(payload.delta||'');if(pending&&pending.pending&&chunk){pending.reasoningText=`${pending.reasoningText||''}${chunk}`.replace(/\s+/g,' ').trim();renderChat()}return}if(name==='answer')return;if(name==='final'){sawFinal=true;state.chatSessionId=payload.session_id||state.chatSessionId;state.conversation=Array.isArray(payload.messages)?payload.messages:[];renderChat();return}if(name==='error'){throw new Error(payload.detail||'Stream failed')}};while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});buffer=buffer.replace(/\r\n/g,'\n');let boundary=buffer.indexOf('\n\n');while(boundary!==-1){const rawEvent=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);for(const line of rawEvent.split('\n')){if(!line)continue;if(line.startsWith('event:')){eventName=line.slice(6).trim();continue}if(line.startsWith('data:'))dataLines.push(line.slice(5).trimStart())}if(dataLines.length)dispatch(eventName,JSON.parse(dataLines.join('\n')));eventName='message';dataLines=[];boundary=buffer.indexOf('\n\n')}if(done)break}if(!sawFinal)throw new Error('Chat stream ended before the final response arrived')}
"""

_EVENT_BINDINGS = r"""themeToggle.addEventListener('click',()=>{document.body.classList.toggle('dark');const isDark=document.body.classList.contains('dark');themeToggle.innerHTML=isDark?lightIcon:darkIcon;themeToggle.setAttribute('aria-label',isDark?'Toggle light mode':'Toggle dark mode')});
logoutButton.addEventListener('click',async()=>{try{const payload=await api('/api/auth/logout',{method:'POST'});state.csrfToken=String(payload?.csrf_token||state.csrfToken||'')}catch(error){setMessage(authMessage,error.message,'error')}state.session={authenticated:false};state.isBooting=false;resetSignedInState();renderSession()});
loginButton?.addEventListener('click',()=>{state.isBooting=true;renderSession()});
claimInviteButton?.addEventListener('click',async()=>{if(state.isClaimingInvite)return;state.isClaimingInvite=true;renderSession();try{state.session=await api('/api/auth/invite/claim',{method:'POST'});state.csrfToken=String(state.session?.csrf_token||state.csrfToken||'');setMessage(authMessage,'Invite claimed.');renderSession();await Promise.allSettled([refreshChatSession(),refreshWorkspace(),isAdmin()?refreshAdminUsers():Promise.resolve()])}catch(error){state.isClaimingInvite=false;renderSession();setMessage(authMessage,error.message,'error')}});
chatInput.addEventListener('input',()=>{chatSubmit.setAttribute('aria-disabled',(!chatInput.value.trim()||state.isStreaming||!signedIn())?'true':'false')});
chatForm.addEventListener('submit',async event=>{event.preventDefault();const message=chatInput.value.trim();if(!message)return;if(!signedIn()){setMessage(chatMessage,'Please sign in first.','error');return}const workspacePathBeforeTurn=currentWorkspacePath();state.stopRequested=false;state.stopIntent=false;state.conversation.push({role:'user',content:message},{role:'assistant',content:'',pending:true,reasoningText:''});chatInput.value='';state.isStreaming=true;renderChat();setMessage(chatMessage,'Streaming response...');let holdStopIntent=false;try{await streamChatTurn(message);setMessage(chatMessage,'Response received.');await refreshWorkspace(workspacePathBeforeTurn)}catch(error){state.conversation=state.conversation.filter(message=>!message.pending);const errorText=String(error?.message||'');const stopLikeError=state.stopIntent||state.stopRequested||Boolean(state.chatAbortController?.signal?.aborted)||String(chatMessage?.textContent||'').includes('Stopping response')||error?.name==='AbortError'||errorText.includes('Connection reset by peer')||errorText.includes('The operation was aborted');if(stopLikeError){holdStopIntent=true;setMessage(chatMessage,'Response stopped.');scheduleStoppedMessage();await sleep(250);await Promise.allSettled([refreshChatSession({preserveMessage:true}),refreshWorkspace(workspacePathBeforeTurn)])}else{setMessage(chatMessage,error.message,'error');await Promise.allSettled([refreshChatSession(),refreshWorkspace(workspacePathBeforeTurn)])}}finally{state.chatAbortController=null;state.isStreaming=false;state.stopRequested=false;if(holdStopIntent){window.setTimeout(()=>{state.stopIntent=false},1500)}else{state.stopIntent=false}renderChat()}});
chatStop.addEventListener('click',async()=>{if(!state.isStreaming)return;state.stopRequested=true;state.stopIntent=true;setMessage(chatMessage,'Stopping response...');scheduleStoppedMessage();try{await api('/api/chat/turn/stop',{method:'POST'})}catch(error){}finally{state.chatAbortController?.abort()}});
workspaceUploadButton.addEventListener('click',()=>{if(workspaceFileInput.disabled)return;workspaceFileInput.click()});
workspaceFileInput.addEventListener('change',async()=>{if(workspaceFileInput.files?.length)await uploadWorkspaceFiles(workspaceFileInput.files)});
workspaceUploadForm.addEventListener('submit',async event=>{event.preventDefault();if(workspaceFileInput.files?.length)await uploadWorkspaceFiles(workspaceFileInput.files)});
workspaceFolderButton.addEventListener('click',()=>{const nextOpen=workspaceFolderForm.hidden;setWorkspaceFolderFormOpen(nextOpen);if(nextOpen)workspaceFolderName.focus()});
workspaceFolderForm.addEventListener('submit',async event=>{event.preventDefault();if(!signedIn()){setMessage(workspaceMessage,'Please sign in first.','error');return}const name=workspaceFolderName.value.trim();if(!name){setMessage(workspaceMessage,'Folder name is required.','error');return}state.isCreatingFolder=true;renderWorkspace();try{state.workspace=normalizeWorkspace(await api('/api/workspace/folders',{method:'POST',body:JSON.stringify({path:currentWorkspacePath(),name})}));workspaceFolderName.value='';setWorkspaceFolderFormOpen(false);setMessage(workspaceMessage,'Folder created.')}catch(error){setMessage(workspaceMessage,error.message,'error')}finally{state.isCreatingFolder=false;renderWorkspace()}});
workspaceUpButton.addEventListener('click',async()=>{const current=currentWorkspacePath();if(!current)return;const parts=current.split('/').filter(Boolean);parts.pop();await refreshWorkspace(parts.join('/'))});
workspaceUpButton.addEventListener('dragover',event=>{if(!currentDraggedWorkspacePath(event))return;event.preventDefault();workspaceUpButton.classList.add('is-drop-target')});
workspaceUpButton.addEventListener('dragleave',()=>workspaceUpButton.classList.remove('is-drop-target'));
workspaceUpButton.addEventListener('drop',async event=>{const draggedPath=currentDraggedWorkspacePath(event);if(!draggedPath)return;event.preventDefault();workspaceUpButton.classList.remove('is-drop-target');const current=currentWorkspacePath();const parts=current.split('/').filter(Boolean);parts.pop();await moveWorkspaceItem(draggedPath,parts.join('/'))});
workspaceTable.addEventListener('dragstart',event=>{const target=event.target;if(!(target instanceof HTMLElement))return;const entry=target.closest('.workspace-entry');if(!(entry instanceof HTMLElement))return;const path=entry.getAttribute('data-path')||'';if(!path)return;state.draggedWorkspacePath=path;event.dataTransfer?.setData('text/plain',path);event.dataTransfer&&(event.dataTransfer.effectAllowed='move')});
workspaceTable.addEventListener('dragend',()=>{state.draggedWorkspacePath='';clearWorkspaceMoveTargets()});
workspaceTable.addEventListener('dragover',event=>{if(!currentDraggedWorkspacePath(event))return;const target=event.target;if(!(target instanceof HTMLElement))return;const folderTarget=target.closest('.workspace-folder-drop-target, .workspace-open-button');if(!(folderTarget instanceof HTMLElement))return;const kind=folderTarget.getAttribute('data-kind')||'';if(kind!=='folder')return;event.preventDefault();clearWorkspaceMoveTargets();folderTarget.classList.add('is-drop-target');const entry=folderTarget.closest('.workspace-entry');entry&&entry.classList.add('is-drop-target')});
workspaceTable.addEventListener('dragleave',event=>{const target=event.target;if(!(target instanceof HTMLElement))return;const related=event.relatedTarget;if(related instanceof Node&&target.contains(related))return;const folderTarget=target.closest('.workspace-folder-drop-target, .workspace-open-button, .workspace-entry');if(folderTarget instanceof HTMLElement)folderTarget.classList.remove('is-drop-target')});
workspaceTable.addEventListener('drop',async event=>{const draggedPath=currentDraggedWorkspacePath(event);if(!draggedPath)return;const target=event.target;if(!(target instanceof HTMLElement))return;const folderTarget=target.closest('.workspace-folder-drop-target, .workspace-open-button');if(!(folderTarget instanceof HTMLElement))return;const kind=folderTarget.getAttribute('data-kind')||'';if(kind!=='folder')return;event.preventDefault();const destinationPath=folderTarget.getAttribute('data-path')||'';await moveWorkspaceItem(draggedPath,destinationPath)});
workspaceTable.addEventListener('click',async event=>{const target=event.target;if(!(target instanceof HTMLElement))return;const openButton=target.closest('.workspace-open-button');if(openButton instanceof HTMLElement){await refreshWorkspace(openButton.getAttribute('data-path')||'');return}const deleteButton=target.closest('.workspace-delete-button');if(!(deleteButton instanceof HTMLElement))return;const path=deleteButton.getAttribute('data-path')||'';try{state.workspace=normalizeWorkspace(await api('/api/workspace/delete',{method:'POST',body:JSON.stringify({path})}));setMessage(workspaceMessage,'Deleted.')}catch(error){setMessage(workspaceMessage,error.message,'error')}renderWorkspace()});
['dragenter','dragover'].forEach(eventName=>workspaceDropzone.addEventListener(eventName,event=>{event.preventDefault();if(!signedIn())return;workspaceDropzone.classList.add('is-active')}));
['dragleave','dragend','drop'].forEach(eventName=>workspaceDropzone.addEventListener(eventName,event=>{event.preventDefault();if(eventName!=='drop')workspaceDropzone.classList.remove('is-active')}));
workspaceDropzone.addEventListener('drop',async event=>{const files=event.dataTransfer?.files;if(files?.length)await uploadWorkspaceFiles(files)});
adminCreateUserForm.addEventListener('submit',async event=>{event.preventDefault();adminCreateUserButton.disabled=true;try{const payload=await api('/api/admin/users',{method:'POST',body:JSON.stringify({display_name:adminDisplayNameInput.value.trim()||null})});state.signupLink=payload.signup?.signup_url||'';adminDisplayNameInput.value='';renderAdmin();setMessage(adminMessage,'Invite link created.');await refreshAdminUsers(true)}catch(error){setMessage(adminMessage,error.message,'error')}finally{adminCreateUserButton.disabled=false}});
adminCopySignupLinkButton.addEventListener('click',async()=>{if(!state.signupLink)return;try{await navigator.clipboard.writeText(state.signupLink);setMessage(adminMessage,'Invite link copied.')}catch(error){setMessage(adminMessage,'Could not copy the invite link.','error')}});
adminUsersTable.addEventListener('click',async event=>{const target=event.target;if(!(target instanceof HTMLElement))return;const button=target.closest('.admin-deactivate-button');if(!(button instanceof HTMLElement))return;const userId=button.getAttribute('data-user-id')||'';if(!userId)return;button.setAttribute('disabled','disabled');try{await api(`/api/admin/users/${encodeURIComponent(userId)}/deactivate`,{method:'POST'});setMessage(adminMessage,'User deactivated.');await refreshAdminUsers(true)}catch(error){setMessage(adminMessage,error.message,'error')}finally{button.removeAttribute('disabled')}});
window.addEventListener('pageshow',()=>{state.session=null;state.isBooting=true;resetSignedInState();renderSession();refreshAll()});
refreshAll();
"""

PAGE_SCRIPT = "\n\n".join(
    (
        _SCRIPT_HEADER,
        _UTILITY_FUNCTIONS,
        _RENDER_FUNCTIONS,
        _DATA_LOADING_FUNCTIONS,
        _ACTION_FUNCTIONS,
        _EVENT_BINDINGS,
    )
)
